### ISSUE TITLE
Logged in this morning to an empty harddrive

### ISSUE THREAD

**Issue by RunR-Chief** [hackerwars-io/issue-tracker#67]
![chrome_amjJRgauG7](https://user-images.githubusercontent.com/69715588/90310468-80d84b80-debf-11ea-826e-ed7834c314e5.png)
![chrome_GsGiXRL6xx](https://user-images.githubusercontent.com/69715588/90310474-846bd280-debf-11ea-9deb-cfac3a60a3a2.png)

I was just on last night and I logged in this morning to a completely wiped HD. I had nearly 4.1GB worth of software. The bitcoin wallet and everything is missing. You cannot delete that bitcoin wallet. I am having to start from scratch just to be able to play. Nobody logged into my account and nobody would spend 30+ minutes deleting everything i had. What is the point in that? I was still logged into a server when i got off. I was downloading new files and it was taking a while so i let it go overnight. They finished i logged in to get them and even though i have the username and password for the server, it would not let me sign in. It said i did not have the necessary software to complete the task. I checked my server and all my software including the bitcoin wallet was gone. I had one piece of software that i couldn't delete myself that was gone too. Huge bug that needs to be addressed. This game is fun, but when you have to start from scratch after you got wiped by the game for no reason it is almost reason to stop playing. I had all my logs cleared on all servers i went to, so unless someone was just trying random IPs and got mine and deleted everything, then there was a bug that wiped my whole HD. Please fix this.

**Comment by hackerwars** [comment]
Unsure what happened, here it may be possible someone has hidden all of your software and or you may have accidentally reformatted your HDD. Unfortunately it is too late since the report for me to dig deeper. I'm unaware of anyone else who has experienced this issue. Given that you were connected to a server downloading software, someone may have been able to reveal the IP for your server using the `nmap` software, so you may not have been safe even though you cleared your logs.
